### ISSUE TITLE
 Error: encoding/hex: odd length hex string

### ISSUE THREAD

**Issue by mrdadah** [Coccodrillo/apns#33]
Hello sir ..

I used your library to push notification to ios devices but I get that error :
 Error: encoding/hex: odd length hex string

this is my code which I got from your documentation example
## can you help me please  

package main
import (
    "fmt"
    apns "github.com/anachronistic/apns"
)
func main() {
    payload := apns.NewPayload()
    payload.Alert = "Hello, world!"
    payload.Badge = 42
    payload.Sound = "default"

```
pn := apns.NewPushNotification()
pn.DeviceToken = "84678103 de0bda6d df26349a d2cda004 0bfe951d c0a9e993 022406e8 0f161c78"
pn.AddPayload(payload)

client := apns.NewClient("gateway.sandbox.push.apple.com:2195", "pushcahrtcert.pem", "pushchatkey.pem")
resp := client.Send(pn)

alert, _ := pn.PayloadString()
fmt.Println("  Alert:", alert)
fmt.Println("Success:", resp.Success)
fmt.Println("  Error:", resp.Error)
```

}

---

**Comment by wfreeman** [comment]
You have spaces in your token. Take them out.
