### ISSUE TITLE
support title in alert struct?

### ISSUE THREAD

**Issue by AdriVanHoudt** [Coccodrillo/apns#37]
as described in https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html under `Table 3-2  Child properties of the alert property`

**Comment by AdriVanHoudt** [comment]
If you want I can do a pr for this

**Comment by Coccodrillo** [comment]
@AdriVanHoudt No, it's fine, I will do it myself. Thank you for reminding me.

**Comment by AdriVanHoudt** [comment]
cool thanks! :+1:
